# Generated by Django 5.2.5 on 2025-08-17 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Menu Assignment',
                'verbose_name_plural': 'User Menu Assignments',
                'db_table': 'user_menu_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='roles_name_a96913_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Optional email address. Must be unique if provided.', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of the role', max_length=150, unique=True, verbose_name='name'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['role'], name='accounts_role_id_8b4a51_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_staff'], name='accounts_is_staf_01c4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone_number', 'is_active'], name='accounts_phone_n_8ade53_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['visibility'], name='menus_visibil_84bc83_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_name'], name='menus_menu_na_643434_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['display_order', 'visibility'], name='menus_display_29af2f_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['depth', 'parent'], name='menus_depth_c179ad_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_url'], name='menus_menu_ur_233a72_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_predefined', 'name'], name='roles_is_pred_ab7810_idx'),
        ),
        migrations.AddIndex(
            model_name='rolemenupermission',
            index=models.Index(fields=['menu', 'role'], name='role_menu_p_menu_id_65e281_idx'),
        ),
        migrations.AddIndex(
            model_name='rolemenupermission',
            index=models.Index(fields=['can_view'], name='role_menu_p_can_vie_ea116d_idx'),
        ),
        migrations.AddIndex(
            model_name='rolemenupermission',
            index=models.Index(fields=['can_create', 'can_update', 'can_delete'], name='role_menu_p_can_cre_0bba0b_idx'),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.menu'),
        ),
        migrations.AddIndex(
            model_name='usermenuassignment',
            index=models.Index(fields=['account', 'assigned_at'], name='user_menu_a_account_6ef210_idx'),
        ),
        migrations.AddIndex(
            model_name='usermenuassignment',
            index=models.Index(fields=['menu', 'assigned_at'], name='user_menu_a_menu_id_04d98e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermenuassignment',
            index=models.Index(fields=['assigned_by'], name='user_menu_a_assigne_8c11ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermenuassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('menu__isnull', False)), fields=('account', 'menu'), name='unique_user_menu_assignment'),
        ),
    ]
