# Generated by Django 5.2.5 on 2025-08-17 12:42

import django.db.models.deletion
import django.utils.timezone
import utilities.global_functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermenuassignment_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenuassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Status to check if the entity is active'),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='reference_id',
            field=models.CharField(db_index=True, default=utilities.global_functions.generate_uuid, editable=False, help_text='Unique identifier for external reference', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermenuassignment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
