# Generated by Django 5.2.5 on 2025-08-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermenuassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenuassignment',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='can_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermenuassignment',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
