# Generated by Django 5.2.5 on 2025-08-16 03:16

import django.db.models.deletion
import utilities.global_functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(db_index=True, default=utilities.global_functions.generate_uuid, editable=False, help_text='Unique identifier for external reference', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Status to check if the entity is active')),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=0, help_text='Higher weight = higher priority')),
                ('color', models.CharField(default='#28a745', help_text='Hex color code for UI', max_length=7)),
                ('sla_hours', models.PositiveIntegerField(blank=True, help_text='SLA response time in hours', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default priority for new tickets')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Priority',
                'verbose_name_plural': 'Ticket Priorities',
                'db_table': 'ticket_priorities',
                'ordering': ['-weight', 'name'],
            },
        ),
    ]
