# Generated by Django 5.2.5 on 2025-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when staff first responded to the ticket', null=True),
        ),
    ]
