# Generated by Django 5.2.5 on 2025-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_first_response_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
