# Generated by Django 5.2.5 on 2025-08-17 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermenuassignment_alter_account_options_and_more'),
        ('tickets', '0005_alter_ticket_is_escalated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sla_breached',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='code',
            field=models.CharField(db_index=True, help_text='Short code for programmatic reference', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='color',
            field=models.CharField(default='#28a745', help_text='Hex color code for UI display (e.g., #28a745)', max_length=7),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed explanation of this priority level'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Default priority for new tickets (only one priority can be default)'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='name',
            field=models.CharField(db_index=True, help_text='Display name of the priority level', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='sla_hours',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='SLA response time in hours (leave blank for no SLA)', null=True),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='weight',
            field=models.IntegerField(db_index=True, default=0, help_text='Higher weight = higher priority (used for sorting)'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='code',
            field=models.CharField(db_index=True, help_text="Short code for programmatic reference (e.g., 'OPEN')", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed explanation of this status and when it should be used'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Default status for new tickets (only one status can be default)'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='name',
            field=models.CharField(db_index=True, help_text="Display name of the status (e.g., 'Open', 'In Progress')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='status_type',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, help_text='Business classification of this status', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='weight',
            field=models.IntegerField(db_index=True, default=0, help_text='Lower weight = higher priority in sorting (0=highest priority)'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_escalated', 'status'], name='tickets_tic_is_esca_17df03_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['menu', 'status'], name='tickets_tic_menu_id_b65765_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['due_date'], name='tickets_tic_due_dat_eb91c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_due_date'], name='tickets_tic_sla_due_061dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_for', 'status'], name='tickets_tic_created_0def1a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketpriority',
            index=models.Index(fields=['weight', 'is_default'], name='ticket_prio_weight_f5943b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketpriority',
            index=models.Index(fields=['sla_hours', 'is_default'], name='ticket_prio_sla_hou_2b7b50_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatus',
            index=models.Index(fields=['status_type', 'weight'], name='ticket_stat_status__8ef313_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatus',
            index=models.Index(fields=['is_default', 'weight'], name='ticket_stat_is_defa_c70bdd_idx'),
        ),
    ]
